# Generated by Django 4.2.2 on 2023-06-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=50, verbose_name='Элемент')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('water_soluble', models.BooleanField(verbose_name='Водорастворимость')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
    ]
