# Generated by Django 4.2.2 on 2023-06-25 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('deadline', models.DateField(help_text='Введите дату в формате ГГГГ-ММ-ДД', verbose_name='Срок')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='wine_photos', verbose_name='Фото')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.plan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Вино',
                'verbose_name_plural': 'Вина',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('location', models.CharField(max_length=100, verbose_name='Расположение')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.plan', verbose_name='План')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание риска')),
                ('risk_type', models.CharField(choices=[('not_danger', 'Not Danger'), ('danger', 'Danger'), ('very_danger', 'Very Danger')], max_length=20, verbose_name='Тип риска')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.plan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Риск',
                'verbose_name_plural': 'Риски',
            },
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст совета')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.plan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Совет',
                'verbose_name_plural': 'Советы',
            },
        ),
    ]
