# Generated by Django 4.2.2 on 2023-06-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_plan_wine_task_risk_advice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
